[package]
authors = ["Cyril Plisko <cyril.plisko@mountall.com>"]
categories = ["development-tools::cargo-plugins"]
description = "Extends cargo to query crates.io registry for crates details"
documentation = "https://docs.rs/cargo-info"
keywords = ["cargo", "info", "subcommand"]
license = "Apache-2.0/MIT"
name = "cargo-info"
repository = "https://gitlab.com/imp/cargo-info.git"
version = "0.5.18"
edition = "2018"

[badges]
travis-ci = { repository = "imp/cargo-info" }
gitlab = { repository = "imp/cargo-info" }

[dependencies]
chrono = "0.4.11"
chrono-humanize = "0.0.11"
json = "0.12.4"
serde = "1.0.111"
serde_json = "1.0.53"
structopt = "0.3.14"
async-std = { version = "1.6.0", features = ["unstable", "attributes"] }
surf = "1.0.3"

[features]
default = []
