on: [push, pull_request]

name: CI

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy
    - name: Run Rustfmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check
    - name: Run Clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
  build_and_test:
    name: Test
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: "1"
      RUSTFLAGS: "-D dead_code -D unused-variables -D unused"
    steps:
      - uses: actions/checkout@master
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -- info serde
